apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 7777